SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    MANAGER_ID,
    SALARY
FROM 
    HR.employees
WHERE 
    MANAGER_ID = 121
    AND COMMISSION_PCT IS NULL
ORDER BY 
    SALARY DESC 
FETCH FIRST 4 ROWS ONLY;
