SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    COMMISSION_PCT
FROM 
    HR.employees
WHERE 
    (SALARY < 3300 OR SALARY > 7500)
    AND COMMISSION_PCT IS NULL
ORDER BY 
    FIRST_NAME ASC, 
    LAST_NAME DESC;