SELECT
   EMPLOYEE_ID,
   FIRST_NAME,
   LAST_NAME,
   COMMISSION_PCT,
   HIRE_DATE,
   LAST_DAY(HIRE_DATE) AS END_OF_MONTH
FROM
   HR.employees
WHERE
   DEPARTMENT_ID NOT IN (60, 90)
   AND NVL(COMMISSION_PCT, 0) = 0;
