SELECT
   EMPLOYEE_ID,
   FIRST_NAME,
   LAST_NAME,
   COMMISSION_PCT,
   HIRE_DATE,
   ROUND((SYSDATE - HIRE_DATE) / 7) AS NUM_OF_WEEKS
   HR.employees
WHERE
   COMMISSION_PCT >= 0.25
   AND LOWER(FIRST_NAME) LIKE '%s%';
