SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    DEPARTMENT_ID,
    NVL(COMMISSION_PCT, 0) AS COMMISSION_PCT,
    SALARY + CASE 
                WHEN NVL(COMMISSION_PCT, 0) BETWEEN 0 AND 0.25 THEN SALARY * 0.2
                WHEN NVL(COMMISSION_PCT, 0) BETWEEN 0.25 AND 0.5 THEN SALARY * 0.4
                WHEN NVL(COMMISSION_PCT, 0) >= 0.5 THEN SALARY * 0.6
             END AS TOTAL
FROM
    HR.employees
ORDER BY 
    NVL(COMMISSION_PCT, 0) ASC;
