SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    TO_CHAR(SALARY, '$999,999') AS SALARY
FROM 
    HR.employees
WHERE 
    MANAGER_ID NOT IN (122, 123)
    AND NVL(COMMISSION_PCT, 0) = 0
ORDER BY 
    SALARY DESC;
