SELECT 
    FIRST_NAME,
    LAST_NAME,
    TO_CHAR(HIRE_DATE, 'DD/MM/YYYY') AS HIRE_DATE,
    NVL2(COMMISSION_PCT, 1, 0) AS COMMISSION
FROM
    HR.employees
WHERE
    TO_CHAR(HIRE_DATE, 'DD') = '07' 
    AND TO_CHAR(HIRE_DATE, 'YYYY') != '2016';
